### ISSUE TITLE
ImageCropperDelegate warning missing

### ISSUE THREAD

**Issue by filippo-basso** [iosdeveloper/ImageCropper#1]
Hi Max,
   and thank you for sharing this nice code! One small thing, please correct this line in your ImageCropper.h, or XCode doesn't complain if the delegate class is not implementing the right protocol (formal protocol that you defined properly).

@property (nonatomic, assign) id &lt;ImageCropperDelegate&gt; delegate;

thank you!
phy

**Comment by ghost** [comment]
iosdeveloper, have you released this under license anywhere? I was going to write something similar for an app I've been contracted for.
